# Generated by Django 4.1.1 on 2022-10-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_deepthought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepthought',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
